# Amount of newest post to show on home page
paginate: 8
paginate_path: "/page:num"
permalink: /:year/:month/:day/:title.html
markdown: redcarpet
# markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
# Fixing highlighting errors: pygments not supported.
highlighter: rouge

is_nav_show: false

# 作者信息
author: 
  name: 吾是锋子
  email: bruce.fend@gmail.com
  link: http://wushifengzi.xyz
 # weibo: 
  github: http://github.com/brucefend
  douban: https://www.douban.com/people/93893839/
 # linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 锋子的房
description: My personal blog
url: http://wushifengzi.xyz
rss_url: /pages/atom.xml
production_url:     http://wushifengzi.xyz           # production_url是sitemap生成的url,方便百度谷歌收录.
is_nav_show: false  #自己加的属性

# gavatar头像及Favicon
gavatar: /public/img/portrait.png
favicon: /public/img/portrait.png

# google analytics 设置
ga:
  id: UA-74985413-1 
  url: wushifengzi.xyz

# disqus 设置
disqus:
  shortname: wushifengzixyz

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - 技术
  - 随笔

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最近
  archive: 归档

